### ISSUE TITLE
Improve ROS log messages

### ISSUE THREAD

**Issue by lorixhack** [Team-Isaac-Polito/reseq_ros2#48]
We want to improve the log messages which ROS produces when launched. In particular, we would like to:

- Reduce INFO messages not very important to understand the status of ROS nodes (for example the messages regarding the position of the robot that are produced every seconds)
- Understand the reasons of nodes' crash (now, when a node crashes, ROS says that it is finished cleanly)
- Making `communication` crash if CAN crashes using lifecycle: [link](https://www.youtube.com/watch?v=_GXHBP5sA70)
- Use other levels of logging like `DEBUG`, `WARN`, `ERROR`, `FATAL`. General information about logging levels here: [link](https://docs.ros.org/en/humble/Concepts/Intermediate/About-Logging.html)
- Set the logging severity level as Launch configuration. See here: [link](https://answers.ros.org/question/311471/selecting-log-level-in-ros2-launch-file/)

**Comment by luca-byte** [comment]
I am quite certain that the nodes with that problem are only internal nodes, in fact I was specifically referring to the communication node. Do you have an example where an external node does that?
